version: "3.8"

services:
  mysql:
    image: mysql:9.0.0-oraclelinux9
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: haydt123
      MYSQL_DATABASE: hay_data
      MYSQL_USER: haydt
      MYSQL_PASSWORD: haydt123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - service_network
  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - service_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user_service_image
    container_name: user_service_container
    depends_on:
      - redis
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hay_data
      SPRING_DATASOURCE_USERNAME: haydt
      SPRING_DATASOURCE_PASSWORD: haydt123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - service_network
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api_gateway_image
    container_name: api_gateway_container
    depends_on:
      - redis
      - user-service
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      USER_SERVICE_URI: http://user-service:8081
      PRODUCT_SERVICE_URI: http://product-service:8082
    networks:
      - service_network

  main_webapp_fe:
    build:
      context: ./main-webapp-fe
      dockerfile: Dockerfile
    image: main_webapp_fe_image
    container_name: main_webapp_fe_container
    depends_on:
      - user-service
      - api-gateway
    ports:
      - "80:80"
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
    name: service_network

volumes:
  mysql_data:
    name: mysql_data
  redis_data:
    name: redis_data
