version: "3.8"

services:
  app:
    build:
      context: ./test-service
      dockerfile: Dockerfile
    image: test-service-image:v1
    container_name: test-service-container
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
