version: "3.8"

services:
  kong-db:
    image: postgres:16-alpine3.20
    container_name: kong-db
    restart: always
    volumes:
      - kong-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    networks:
      - kong-network

  kong-migrations:
    image: kong/kong-gateway:3.3-alpine
    container_name: kong-migrations
    depends_on:
      - kong-db
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PORT: 5432
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks:
      - kong-network
    command: kong migrations bootstrap

  kong:
    image: kong/kong-gateway:3.3-alpine
    container_name: kong-gateway
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000" # Proxy API
      - "8443:8443" # Proxy API (HTTPS)
      - "8001:8001" # Admin API
      - "8444:8444" # Admin API (HTTPS)
      - "8002:8002" # Admin GUI
      - "8445:8445" # Admin GUI (HTTPS)
      - "8003:8003" # Another port
      - "8004:8004" # Another port
    depends_on:
      - kong-db
      - kong-migrations
    networks:
      - kong-network

volumes:
  kong-db-data:

networks:
  kong-network:
    driver: bridge
    name: kong-network
