version: "3.8"

services:
  mysql:
    image: mysql:9.0.0-oraclelinux9
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: haydt123
      MYSQL_DATABASE: hay_data
      MYSQL_USER: haydt
      MYSQL_PASSWORD: haydt123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - service_network
  redis:
    image: redis:7.2.5-alpine3.20
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - service_network
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  postgresql:
    image: bitnami/postgresql:16
    container_name: postgresql_container
    restart: always
    environment:
      POSTGRESQL_USERNAME: haydt
      POSTGRESQL_PASSWORD: haydt123
      POSTGRESQL_DATABASE: keycloak
      POSTGRESQL_POSTGRES_PASSWORD: haydt123
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - service_network

  keycloak:
    image: bitnami/keycloak:24
    container_name: keycloak_container
    environment:
      KEYCLOAK_ADMIN: haydt
      KEYCLOAK_ADMIN_PASSWORD: haydt123
      KEYCLOAK_DATABASE_HOST: postgresql
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_VENDOR: postgresql
      KEYCLOAK_DATABASE_USER: haydt
      KEYCLOAK_DATABASE_PASSWORD: haydt123
      KEYCLOAK_DATABASE_NAME: keycloak
      KEYCLOAK_HTTP_PORT: 8888
      KEYCLOAK_HTTPS_PORT: 9999
    depends_on:
      - postgresql
    ports:
      - 8000:8888
      - 9999:9999

    networks:
      - service_network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user_service_image
    container_name: user_service_container
    depends_on:
      - redis
      - mysql
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hay_data
      SPRING_DATASOURCE_USERNAME: haydt
      SPRING_DATASOURCE_PASSWORD: haydt123
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    networks:
      - service_network
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: api_gateway_image
    container_name: api_gateway_container
    depends_on:
      - redis
      - user-service
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      USER_SERVICE_URI: http://user-service:8081
      PRODUCT_SERVICE_URI: http://product-service:8082
    networks:
      - service_network

  main_webapp_fe:
    build:
      context: ./main-webapp-fe
      dockerfile: Dockerfile
    image: main_webapp_fe_image
    container_name: main_webapp_fe_container
    depends_on:
      - user-service
      - api-gateway
    ports:
      - "80:80"
    networks:
      - service_network

networks:
  service_network:
    driver: bridge
    name: service_network

volumes:
  mysql_data:
    name: mysql_data
  redis_data:
    name:
  postgresql_data:
    name: postgresql_data
