version: "3.8"

services:
  mysql:
    image: mysql:9.0.0-oraclelinux9
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: haydt123
      MYSQL_DATABASE: hay_data
      MYSQL_USER: haydt
      MYSQL_PASSWORD: haydt123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - service_network

  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: user_service_image
    container_name: user_service_container
    depends_on:
      - mysql
    ports:
      - "8888:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hay_data
      SPRING_DATASOURCE_USERNAME: haydt
      SPRING_DATASOURCE_PASSWORD: haydt123
    networks:
      - service_network

  main_webapp_fe:
    build:
      context: ./main-webapp-fe
      dockerfile: Dockerfile
    image: main_webapp_fe_image
    container_name: main_webapp_fe_container
    depends_on:
      - user_service
    ports:
      - "80:80"
    networks:
      - service_network

networks:
  service_network:
    driver: bridge

volumes:
  db_data:
